/*
 * OperatorRCBridge.hpp
 *
 *  Created on: May 10, 2016
 *      Author: zeeuwe01
 */

#ifndef OPERATORRCBRIDGE_HPP_
#define OPERATORRCBRIDGE_HPP_

#include "ros/ros.h"
#include "geometry_msgs/Twist.h"
#include "mavros_msgs/RCIn.h"
#include "std_msgs/Bool.h"
#include "std_msgs/String.h"
#include "string"
#include <stdio.h>
#include <string.h>
#include <array>

#include "OperatorLowLevel.hpp"
#include "OperatorPublisher.hpp"

extern geometry_msgs::Twist* propulsionMessage;
extern geometry_msgs::Twist* conveyorMessage;

using namespace std;

#define CHANNEL_MEDIAN (1500)
#define CHANNEL_TOLLERANCE (50)
#define CHANNEL_MIN_THRESHOLD (CHANNEL_MEDIAN-CHANNEL_TOLLERANCE)
#define CHANNEL_MAX_THRESHOLD (CHANNEL_MEDIAN+CHANNEL_TOLLERANCE)

#define CHANNEL_DIFMOTOR_PROPULSION (0)
#define CHANNEL_DIFMOTOR_PROPULSION_MAX (1900)
#define CHANNEL_DIFMOTOR_PROPULSION_MIN (1100)
#define CHANNEL_DIFMOTOR_PROPULSION_POSITIVE_RANGE (CHANNEL_DIFMOTOR_PROPULSION_MAX - CHANNEL_MEDIAN)
#define CHANNEL_DIFMOTOR_PROPULSION_NEGATIVE_RANGE (CHANNEL_MEDIAN - CHANNEL_DIFMOTOR_PROPULSION_MIN)

#define CHANNEL_DIFMOTOR_STEERING (1)
#define CHANNEL_DIFMOTOR_STEERING_MAX (1800)
#define CHANNEL_DIFMOTOR_STEERING_MIN (1200)
#define CHANNEL_DIFMOTOR_STEERING_POSITIVE_RANGE (CHANNEL_DIFMOTOR_STEERING_MAX - CHANNEL_MEDIAN)
#define CHANNEL_DIFMOTOR_STEERING_NEGATIVE_RANGE (CHANNEL_MEDIAN - CHANNEL_DIFMOTOR_STEERING_MIN)

#define CHANNEL_CONVEYOR_ACTIVATION (2)
#define CHANNEL_CONVEYOR_ACTIVATION_MAX (1800)
#define CHANNEL_CONVEYOR_ACTIVATION_MIN (1200)
#define CHANNEL_CONVEYOR_ACTIVATION_POSITIVE_RANGE (CHANNEL_CONVEYOR_ACTIVATION_MAX - CHANNEL_MEDIAN)
#define CHANNEL_CONVEYOR_ACTIVATION_NEGATIVE_RANGE (CHANNEL_MEDIAN - CHANNEL_CONVEYOR_ACTIVATION_MIN)

#define CHANNEL_CONVEYOR_STEER (3)
#define CHANNEL_CONVEYOR_STEER_MAX (1800)
#define CHANNEL_CONVEYOR_STEER_MIN (1200)
#define CHANNEL_CONVEYOR_STEER_POSITIVE_RANGE (CHANNEL_CONVEYOR_STEER_MAX - CHANNEL_MEDIAN)
#define CHANNEL_CONVEYOR_STEERNEGATIVE_RANGE (CHANNEL_MEDIAN - CHANNEL_CONVEYOR_STEER_MIN)

#define CHANNEL_TAKEOVER (4)
#define CHANNEL_TAKEOVER_MAX (1900)
#define CHANNEL_TAKEOVER_MIN (1100)
#define CHANNEL_TAKEOVER_POSITIVE_RANGE (CHANNEL_TAKEOVER_MAX - CHANNEL_MEDIAN)
#define CHANNEL_TAKEOVER_NEGATIVE_RANGE (CHANNEL_MEDIAN - CHANNEL_TAKEOVER_MIN)

void rcCallback(const mavros_msgs::RCIn::ConstPtr& msg);

#endif /* OPERATORRCBRIDGE_HPP_ */
