// Generated by gencpp from file nautonomous_navigation_planner/AddTwoInts.msg
// DO NOT EDIT!


#ifndef nautonomous_navigation_planner_MESSAGE_ADDTWOINTS_H
#define nautonomous_navigation_planner_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <nautonomous_navigation_planner/AddTwoIntsRequest.h>
#include <nautonomous_navigation_planner/AddTwoIntsResponse.h>


namespace nautonomous_navigation_planner
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace nautonomous_navigation_planner


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::nautonomous_navigation_planner::AddTwoInts > {
  static const char* value()
  {
    return "85b30cd527059fcf2f8d220f22837593";
  }

  static const char* value(const ::nautonomous_navigation_planner::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::nautonomous_navigation_planner::AddTwoInts > {
  static const char* value()
  {
    return "nautonomous_navigation_planner/AddTwoInts";
  }

  static const char* value(const ::nautonomous_navigation_planner::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::nautonomous_navigation_planner::AddTwoIntsRequest> should match 
// service_traits::MD5Sum< ::nautonomous_navigation_planner::AddTwoInts > 
template<>
struct MD5Sum< ::nautonomous_navigation_planner::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::nautonomous_navigation_planner::AddTwoInts >::value();
  }
  static const char* value(const ::nautonomous_navigation_planner::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::nautonomous_navigation_planner::AddTwoIntsRequest> should match 
// service_traits::DataType< ::nautonomous_navigation_planner::AddTwoInts > 
template<>
struct DataType< ::nautonomous_navigation_planner::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::nautonomous_navigation_planner::AddTwoInts >::value();
  }
  static const char* value(const ::nautonomous_navigation_planner::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::nautonomous_navigation_planner::AddTwoIntsResponse> should match 
// service_traits::MD5Sum< ::nautonomous_navigation_planner::AddTwoInts > 
template<>
struct MD5Sum< ::nautonomous_navigation_planner::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::nautonomous_navigation_planner::AddTwoInts >::value();
  }
  static const char* value(const ::nautonomous_navigation_planner::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::nautonomous_navigation_planner::AddTwoIntsResponse> should match 
// service_traits::DataType< ::nautonomous_navigation_planner::AddTwoInts > 
template<>
struct DataType< ::nautonomous_navigation_planner::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::nautonomous_navigation_planner::AddTwoInts >::value();
  }
  static const char* value(const ::nautonomous_navigation_planner::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // nautonomous_navigation_planner_MESSAGE_ADDTWOINTS_H
